In [1]:
import numpy as np

In [2]:
n = np.array(30)
print(n)
print("Dimentions: ", n.ndim)

30
Dimentions:  0


# **Array attributes**
- **ndim**
- **shape**
- **size**
- **dtype**

In [3]:
a = np.array([1, 2, 3])
print(a)
print(type(a))
print("Dimension: ", a.ndim) # number of dimnsions of an array is contained in the ndim attribute

[1 2 3]
<class 'numpy.ndarray'>
Dimension:  1


In [4]:
# Slicing
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(b[0])
print(b[-1])
print(b[3])
print(b[3:])
print(b[:3])


1
10
4
[ 4  5  6  7  8  9 10]
[1 2 3]


In [5]:
print(b.shape)
print(b.ndim)
print(len(b.shape))

(10,)
1
1


In [7]:
print(b.size)
print(b.dtype)

10
int64
